<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    //
    public function makeSocialSignIn(Request $request)
    {
        return view( 'social_sign_in');
    }

    public function handleMakeSocialSignIn(Request $request)
    {
        $input = $request->all();
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v14.0/' . $input['id'] . '/?fields=email,name');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');

        curl_setopt($ch, CURLOPT_POSTFIELDS, "access_token=" . $input['accessToken']);

        $headers = array();
        $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        $result = json_decode($result);
        

        // Check if user exists already
        $user = User::where('email', $result->email)->first();
        if ( $user == null ) {
            // Create new user
            $user = User::create([
                'name' => $result->name,
                'email' => $result->email
            ]);
        }
        Auth::login( $user);
        return redirect('home');
        // redirect()->route('');
    }

    public function home(Request $request)
    {
        return view('home');
    }

    public function logout(Request $request)
    {
        Auth::logout();
        return redirect('social-sign-in');
    }
}
